# Site settings
title: Soy de temporada
email: your-email@domain.com
url: https://ffosset.github.io/journey-of-food
github: https://github.com/ffosset/journey-of-food/
description: "Un calendario de productos de temporada fiable, colaborativo y transparente. Para uso cotidiano. Made in #visualizar17."
keywords: "food, journey, comida, españa, temporada, visualizar"
meta_author: Colaboradores Journey of Food

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: FAFAFA #80B3FF
  primary-complement: 3F3F3F
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 3F3F3F #FD6E8A
  secondary-dark: 233140 #A2122F
  highlight: CA7947

# Footer settings
footer:
  copyright: Medialab Prado
  location: Equipo
  social: Redes
  credits: Contacto

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)

social:
  - title: facebook
    url: http://www.facebook.com/sharer.php?u=[url]
  - title: twitter
    url: https://twitter.com/intent/tweet?text=Un%20calendario%20de%20productos%20de%20temporada%20fiable%2C%20colaborativo%20y%20transparente.%20Para%20uso%20cotidiano.%20Made%20in%20%23visualizar17%20[url]
  - title: linkedin
    url: http://www.linkedin.com/shareArticle?url=[url]


# Credits content
credits: 'visualizar@medialab-prado.es'

collections:
  products:
    output: true
    permalink: /:collection/:name

defaults:
  - scope:
      path: ""
      type: products
    values:
      layout: product


# Build settings
markdown: kramdown
permalink: pretty
