# Site settings
title: Journey of Food
email: your-email@domain.com
url: https://ffosset.github.io/journey-of-food
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
keywords: "food, journey, comida, españa, temporada, visualizar"
skills: "Una herramienta de búsqueda de productos de temporada en tu región"
meta_author: Colaboradores Journey of Food

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: FAFAFA #80B3FF
  primary-complement: 3F3F3F
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 3F3F3F #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Medialab Prado
  location: Equipo
  social: Redes
  credits: Contacto

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/
  - title: github
    url: https://github.com/ffosset/journey-of-food/

# Postal address (add as many lines as necessary)
address:
    - line: <a href="https://twitter.com/lowfill/">Diego Andrés</a>
    - line: <a href="http://fosset.co">Flora Fosset<a/>
    - line: Jimena
    - line: <a href="https://twitter.com/paucc/">Pau Valiente<a/>
    - line: <a href="https://twitter.com/Raiskv">Rai Abril<a/>

# Credits content
credits: 'visualizar@medialab-prado.es'

collections:
  products:
    output: true
    permalink: /:collection/:name

defaults:
  - scope:
      path: ""
      type: products
    values:
      layout: product


# Build settings
markdown: kramdown
permalink: pretty
